version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: ../back/.docker/Back/Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_HOST: "http://backend:4000"
    depends_on:
      - backend

  backend:
    build:
      context: ../back/.docker
      dockerfile: Back/Back.Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://bnovo_test_user:bnovo123456@db:5432/bnovo_test?schema=public"
    depends_on:
      - db

  db:
    build:
      context: ../back/.docker
      dockerfile: DB/DB.Dockerfile
    environment:
      POSTGRES_USER: bnovo_test_user
      POSTGRES_PASSWORD: bnovo123456
      POSTGRES_DB: bnovo_test
    ports:
      - "5432:5432"
